### ISSUE TITLE
Connect to Remote kafka cluster 

### ISSUE THREAD

**Issue by dandamudi1414** [devshawn/kafka-shell#22]
Hi 

Can I connect to a remote Kafka cluster ( not local) using this?

**Comment by devshawn** [comment]
Hi @dandamudi1414, it can connect to any cluster as long as you have access to it (network-wise and authentication wise) through [configuration](https://github.com/devshawn/kafka-shell/blob/master/CONFIGURATION.md).

Here is an example connecting to a Confluent Cloud cluster. 

An example kafka properties file:

```properties
bootstrap.servers=pkc-xxx.us-east-1.aws.confluent.cloud:9092
ssl.endpoint.identification.algorithm=https
sasl.mechanism=PLAIN
request.timeout.ms=20000
retry.backoff.ms=500
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="xxx" password="xxx";
security.protocol=SASL_SSL
```

Example kafka-shell config (`~/.kafka-shell/config.yaml`):
```yaml
version: 1
enable:
  history: true
  save_on_exit: false
  auto_complete: true
  auto_suggest: true
  inline_help: true
  fuzzy_search: true
cluster: remote
clusters:
  remote:
    bootstrap_servers: pkc-xxx.us-east-1.aws.confluent.cloud:9092
    consumer_settings:
      config: /Users/devshawn/remote.properties
    producer_settings:
      config: /Users/devshawn/remote.properties
    admin_client_settings:
      config: /Users/devshawn/remote.properties
```
